// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['idApiKey'] ?? 'CHAVE_PADRÃO',
    appId: dotenv.env['apiID'] ?? 'CHAVE_PADRÃO',
    messagingSenderId: dotenv.env['senderId'] ?? 'CHAVE_PADRÃO',
    projectId: dotenv.env['projectId'] ?? 'CHAVE_PADRÃO',
    storageBucket: dotenv.env['storageName'] ?? 'CHAVE_PADRÃO',
    iosBundleId:  dotenv.env['iosBundleId'] ?? 'CHAVE_PADRÃO',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['idApiKey'] ?? 'CHAVE_PADRÃO',
    appId: dotenv.env['apiID'] ?? 'CHAVE_PADRÃO',
    messagingSenderId: dotenv.env['senderId'] ?? 'CHAVE_PADRÃO',
    projectId: dotenv.env['projectId'] ?? 'CHAVE_PADRÃO',
    storageBucket: dotenv.env['storageName'] ?? 'CHAVE_PADRÃO',
    iosBundleId:  dotenv.env['iosBundleId'] ?? 'CHAVE_PADRÃO',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['idApiKey'] ?? 'CHAVE_PADRÃO',
    appId: dotenv.env['apiID'] ?? 'CHAVE_PADRÃO',
    messagingSenderId: dotenv.env['senderId'] ?? 'CHAVE_PADRÃO',
    projectId: dotenv.env['projectId'] ?? 'CHAVE_PADRÃO',
    authDomain: dotenv.env['authDomain'] ?? 'CHAVE_PADRÃO',
    storageBucket: dotenv.env['storageName'] ?? 'CHAVE_PADRÃO',
  );

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['idApiKey'] ?? 'CHAVE_PADRÃO',
    appId: dotenv.env['apiID'] ?? 'CHAVE_PADRÃO',
    messagingSenderId: dotenv.env['senderId'] ?? 'CHAVE_PADRÃO',
    projectId: dotenv.env['projectId'] ?? 'CHAVE_PADRÃO',
    authDomain: dotenv.env['authDomain'] ?? 'CHAVE_PADRÃO',
    storageBucket: dotenv.env['storageName'] ?? 'CHAVE_PADRÃO',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['idApiKey'] ?? 'CHAVE_PADRÃO',
    appId: dotenv.env['apiID'] ?? 'CHAVE_PADRÃO',
    messagingSenderId: dotenv.env['senderId'] ?? 'CHAVE_PADRÃO',
    projectId: dotenv.env['projectId'] ?? 'CHAVE_PADRÃO',
    storageBucket: dotenv.env['storageName'] ?? 'CHAVE_PADRÃO',
  );

}